const fs = require("fs");

const names = `
CARIDAD SANCHEZ
CARMEN ROSALES
CELESTE LEGASPI
CESAR RAMIREZ
CHANDA ROMERO
CHARITO SOLIS
CHICHAY
CHIQUITO
CLAIRE DELA FUENTE
CORAZON NOBLE
CORAZON RIVAS
Cynthia Luster
DANTE VARONA
DARIA RAMIREZ
DAWN ZULUETA
DEBORAH SUN
DELIA RAZON
DELY ATAY ATAYAN
DENCIO PADILLA
DIDITH REYES
DIOMEDES MATURAN
DIVINA VALENCIA
Dolphy
EDDIE GARCIA
EDDIE MESA
EDDIE RODRIGUEZ
Efren Reyes Sr
ELIZABETH OROPESA
ELIZABETH RAMSEY
FERNANDO POE SR
GINA PAREÑO
GLORIA DIAZ
GLORIA ROMERO
GLORIA SEVILLA
HILDA KORONEL
JAIME DE LA ROSA
JOHNNY MONTEIRO
JOSE MARI GONZALEZ
Joseph ERAP Estrada
JOSEPHINE ESTRADA
JULIE VEGA
LANI OTEYZA
LEOPOLDO SALCEDO
LIBERTY ILAGAN
LILIA DIZON
LIZ ALINDOGAN
LIZA LORENA
LOLITA RODRIGUEZ
LOTA DELGADO
LOTIS KEY
LUIS GONZALES
LUZ VALDEZ
MANDING CLARO
MARGIE MORAN
Mario Montenegro
MARLENE DAUDEN
MARY WALTER
MAX ALVARADO
MIGUEL RODRIGUEZ
MINA ARAGON
MONA LISA
PIPOY
NESTOR DE VILLA
NOYNOY AQUINO
PALITO
PAQUITO DIAZ
PARALUMAN
PATSY PATSOTSAY
PILAR PILAPIL
Pilita Corrales
RICO J PUNO
RICO YAN
RINA REYES
RIO LOCSIN
Rita Gomez
ROGELIO DE LA ROSA
ROMEO VASQUEZ
ROSA DEL ROSARIO
ROSA ROSAL
ROSANNA ORTIZ
ROSITA NOBLE
RUEL VERNAL
SOFIA MORAN
STELLA STRADA
SUBAS HERRERO
SYLVIA LA TORRE
TESSIE AGANA
TESSIE QUINTANA
TETCHIE AGBAYANI
TITA DURAN
TONY FERRER
TONY SANTOS SR
VAN DE LEON
VIC VARGAS
VICTOR WOOD
VIVIAN VELEZ
WENG WENG
ZALDY ZSHORNACK
ZENY ZABALA
`.trim();

const db = names.split("\n").map((n) => ({
  name: n.trim(),
  opened: false,
}));

fs.writeFileSync("database.json", JSON.stringify(db, null, 2), "utf8");

console.log("✔ Created database.json");
